---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /path/to/duplicati/container:/config
      - /path/to/nextcloud/db:/NextcloudDB
      - /path/to/nextcloud:/Nextcloud
      - /path/to/pihole:/Pihole
    ports:
      - 8200:8200
    restart: unless-stopped
