---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=
      - PGID=
      - TZ=Europe/London
    volumes:
      - /path/on/host/machine:/config
    ports:
      - $hostMachinePort:80
      - $hostMachinePort:443
    restart: unless-stopped
